/**
 * A recommended list of common email provider domains, to be used as `domains` in the configuration.
 *
 * Extend it with your own domains: `domains: [...domains, "example.org"]`.
 *
 * The order matters: if a typo is one edit away from several domains, the first one is recommended.
 * The most common providers therefore come first.
 */
export const domains: string[] = [
    // Global providers
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "icloud.com",
    "live.com",
    "aol.com",
    "msn.com",
    "mac.com",
    "googlemail.com",
    "ymail.com",
    "rocketmail.com",
    "proton.me",
    "protonmail.com",
    "mail.com",
    "email.com",
    "gmx.com",
    "gmx.net",
    "zoho.com",
    "zohomail.com",
    "fastmail.com",
    "fastmail.fm",
    "tutanota.com",
    "tuta.com",
    "hey.com",
    "duck.com",
    "yandex.com",

    // Germany
    "web.de",
    "gmx.de",
    "t-online.de",
    "freenet.de",
    "posteo.de",
    "mailbox.org",
    "arcor.de",
    "online.de",
    "magenta.de",
    "mail.de",
    "email.de",
    "vodafone.de",
    "netcologne.de",
    "kabelbw.de",
    "unitybox.de",
    "ewe.net",
    "hotmail.de",
    "outlook.de",
    "live.de",
    "yahoo.de",
    "aol.de",

    // Switzerland
    "bluewin.ch",
    "gmx.ch",
    "hispeed.ch",
    "sunrise.ch",
    "bluemail.ch",
    "swissonline.ch",
    "green.ch",
    "quickline.ch",
    "hotmail.ch",
    "protonmail.ch",

    // Austria
    "gmx.at",
    "aon.at",
    "chello.at",

    // United Kingdom
    "hotmail.co.uk",
    "yahoo.co.uk",
    "live.co.uk",
    "btinternet.com",
    "sky.com",
    "virginmedia.com",
    "ntlworld.com",
    "talktalk.net",
    "blueyonder.co.uk",

    // France
    "orange.fr",
    "hotmail.fr",
    "yahoo.fr",
    "wanadoo.fr",
    "free.fr",
    "sfr.fr",
    "laposte.net",
    "live.fr",
    "outlook.fr",
    "neuf.fr",

    // Italy
    "libero.it",
    "hotmail.it",
    "yahoo.it",
    "virgilio.it",
    "alice.it",
    "tiscali.it",
    "tin.it",
    "live.it",

    // Spain
    "hotmail.es",
    "yahoo.es",
    "outlook.es",
    "telefonica.net",

    // Netherlands and Belgium
    "ziggo.nl",
    "kpnmail.nl",
    "hetnet.nl",
    "planet.nl",
    "home.nl",
    "xs4all.nl",
    "live.nl",
    "telenet.be",
    "skynet.be",

    // North America
    "comcast.net",
    "verizon.net",
    "att.net",
    "sbcglobal.net",
    "bellsouth.net",
    "cox.net",
    "charter.net",
    "earthlink.net",
    "yahoo.ca",
    "shaw.ca",
    "rogers.com",
    "sympatico.ca",

    // Rest of the world
    "mail.ru",
    "yandex.ru",
    "rambler.ru",
    "inbox.ru",
    "list.ru",
    "163.com",
    "126.com",
    "sina.com",
    "naver.com",
    "daum.net",
    "hanmail.net",
    "yahoo.co.jp",
    "yahoo.co.in",
    "rediffmail.com",
    "yahoo.com.br",
    "uol.com.br",
    "bol.com.br",
    "terra.com.br",
    "yahoo.com.au",
    "bigpond.com",
    "optusnet.com.au",
    "interia.pl",
    "onet.pl",
    "seznam.cz",
    "webmail.co.za",
];
